#
# Automagically generated by Approximatrix Simply Fortran
#
FC="C:\Program Files (x86)\Simply Fortran\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran\mingw-w64\bin\ar.exe"
TOUCH="C:\Program Files (x86)\Simply Fortran\fwin\wtouch.exe"
WRC="C:\PROGRA~2\SIMPLY~1\MINGW-~1\bin\windres.exe"
RM=del

IDIR=
# -I error: Directory C:\Program Files (x86)\Simply Fortran\mingw-w64\include\ does not exist
# -I error: Directory C:\Users\sukhveersanghera\Desktop\Gas Turbine Project\CCMD\Default Add-On Include Directory does not exist

LDIR=-LC:/PROGRA~2/SIMPLY~1/MINGW-~1/lib/ 
# -L error: Directory C:\Users\sukhveersanghera\Desktop\Gas Turbine Project\CCMD\Default Add-On Directory does not exist


SPECIALFLAGS=-g $(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=
PRJ_CFLAGS=
PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS)  $(PRJ_FFLAGS) -Jmodules 

CFLAGS=-g  $(IDIR) $(PRJ_CFLAGS)

"build\CORE_MLT.o": ".\REFPROP 9.0 Subroutines\CORE_MLT.FOR"
	$(FC) -c -o "build\CORE_MLT.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_MLT.FOR"

"build\CORE_PH0.o": ".\REFPROP 9.0 Subroutines\CORE_PH0.FOR"
	$(FC) -c -o "build\CORE_PH0.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_PH0.FOR"

"build\CORE_PR.o": ".\REFPROP 9.0 Subroutines\CORE_PR.FOR"
	$(FC) -c -o "build\CORE_PR.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_PR.FOR"

"build\CORE_QUI.o": ".\REFPROP 9.0 Subroutines\CORE_QUI.FOR"
	$(FC) -c -o "build\CORE_QUI.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_QUI.FOR"

"build\CORE_STN.o": ".\REFPROP 9.0 Subroutines\CORE_STN.FOR"
	$(FC) -c -o "build\CORE_STN.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_STN.FOR"

"build\FLASH2.o": ".\REFPROP 9.0 Subroutines\FLASH2.FOR"
	$(FC) -c -o "build\FLASH2.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\FLASH2.FOR"

"build\FLSH_SUB.o": ".\REFPROP 9.0 Subroutines\FLSH_SUB.FOR"
	$(FC) -c -o "build\FLSH_SUB.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\FLSH_SUB.FOR"

"build\IDEALGAS.o": ".\REFPROP 9.0 Subroutines\IDEALGAS.FOR"
	$(FC) -c -o "build\IDEALGAS.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\IDEALGAS.FOR"

"build\MIX_AGA8.o": ".\REFPROP 9.0 Subroutines\MIX_AGA8.FOR"
	$(FC) -c -o "build\MIX_AGA8.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\MIX_AGA8.FOR"

"build\MIX_HMX.o": ".\REFPROP 9.0 Subroutines\MIX_HMX.FOR"
	$(FC) -c -o "build\MIX_HMX.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\MIX_HMX.FOR"

"build\PROP_SUB.o": ".\REFPROP 9.0 Subroutines\PROP_SUB.FOR"
	$(FC) -c -o "build\PROP_SUB.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\PROP_SUB.FOR"

"build\REALGAS.o": ".\REFPROP 9.0 Subroutines\REALGAS.FOR"
	$(FC) -c -o "build\REALGAS.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\REALGAS.FOR"

"build\SAT_SUB.o": ".\REFPROP 9.0 Subroutines\SAT_SUB.FOR"
	$(FC) -c -o "build\SAT_SUB.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\SAT_SUB.FOR"

"build\SETUP.o": ".\REFPROP 9.0 Subroutines\SETUP.FOR"
	$(FC) -c -o "build\SETUP.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\SETUP.FOR"

"build\SETUP2.o": ".\REFPROP 9.0 Subroutines\SETUP2.FOR"
	$(FC) -c -o "build\SETUP2.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\SETUP2.FOR"

"build\TRNS_ECS.o": ".\REFPROP 9.0 Subroutines\TRNS_ECS.FOR"
	$(FC) -c -o "build\TRNS_ECS.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\TRNS_ECS.FOR"

"build\TRNS_TCX.o": ".\REFPROP 9.0 Subroutines\TRNS_TCX.FOR"
	$(FC) -c -o "build\TRNS_TCX.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\TRNS_TCX.FOR"

"build\TRNS_VIS.o": ".\REFPROP 9.0 Subroutines\TRNS_VIS.FOR"
	$(FC) -c -o "build\TRNS_VIS.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\TRNS_VIS.FOR"

"build\TRNSP.o": ".\REFPROP 9.0 Subroutines\TRNSP.FOR"
	$(FC) -c -o "build\TRNSP.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\TRNSP.FOR"

"build\UTILITY.o": ".\REFPROP 9.0 Subroutines\UTILITY.FOR"
	$(FC) -c -o "build\UTILITY.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\UTILITY.FOR"

"build\CORE_ANC.o": ".\REFPROP 9.0 Subroutines\CORE_ANC.FOR"
	$(FC) -c -o "build\CORE_ANC.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_ANC.FOR"

"build\CORE_BWR.o": ".\REFPROP 9.0 Subroutines\CORE_BWR.FOR"
	$(FC) -c -o "build\CORE_BWR.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_BWR.FOR"

"build\CORE_CPP.o": ".\REFPROP 9.0 Subroutines\CORE_CPP.FOR"
	$(FC) -c -o "build\CORE_CPP.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_CPP.FOR"

"build\CORE_DE.o": ".\REFPROP 9.0 Subroutines\CORE_DE.FOR"
	$(FC) -c -o "build\CORE_DE.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_DE.FOR"

"build\CORE_ECS.o": ".\REFPROP 9.0 Subroutines\CORE_ECS.FOR"
	$(FC) -c -o "build\CORE_ECS.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_ECS.FOR"

"build\CORE_FEQ.o": ".\REFPROP 9.0 Subroutines\CORE_FEQ.FOR"
	$(FC) -c -o "build\CORE_FEQ.o" $(FFLAGS) ".\REFPROP 9.0 Subroutines\CORE_FEQ.FOR"

"build\CCMD.o": ".\CCMD.F90"
	$(FC) -c -o "build\CCMD.o" $(FFLAGS) ".\CCMD.F90"

clean: .SYMBOLIC
	$(RM) "build\CORE_MLT.o"
	$(RM) "build\CORE_PH0.o"
	$(RM) "build\CORE_PR.o"
	$(RM) "build\CORE_QUI.o"
	$(RM) "build\CORE_STN.o"
	$(RM) "build\FLASH2.o"
	$(RM) "build\FLSH_SUB.o"
	$(RM) "build\IDEALGAS.o"
	$(RM) "build\MIX_AGA8.o"
	$(RM) "build\MIX_HMX.o"
	$(RM) "build\PASS_FTN.o"
	$(RM) "build\PROP_SUB.o"
	$(RM) "build\REALGAS.o"
	$(RM) "build\SAT_SUB.o"
	$(RM) "build\SETUP.o"
	$(RM) "build\SETUP2.o"
	$(RM) "build\TRNS_ECS.o"
	$(RM) "build\TRNS_TCX.o"
	$(RM) "build\TRNS_VIS.o"
	$(RM) "build\TRNSP.o"
	$(RM) "build\UTILITY.o"
	$(RM) "build\COMMONS.o"
	$(RM) "build\COMTRN.o"
	$(RM) "build\CORE_ANC.o"
	$(RM) "build\CORE_BWR.o"
	$(RM) "build\CORE_CPP.o"
	$(RM) "build\CORE_DE.o"
	$(RM) "build\CORE_ECS.o"
	$(RM) "build\CORE_FEQ.o"
	$(RM) "build\CCMD.o"
	$(RM) "CCMD.exe"

"CCMD.exe":  "build\CORE_MLT.o" "build\CORE_PH0.o" "build\CORE_PR.o" "build\CORE_QUI.o" "build\CORE_STN.o" "build\FLASH2.o" "build\FLSH_SUB.o" "build\IDEALGAS.o" "build\MIX_AGA8.o" "build\MIX_HMX.o" "build\PROP_SUB.o" "build\REALGAS.o" "build\SAT_SUB.o" "build\SETUP.o" "build\SETUP2.o" "build\TRNS_ECS.o" "build\TRNS_TCX.o" "build\TRNS_VIS.o" "build\TRNSP.o" "build\UTILITY.o" "build\CORE_ANC.o" "build\CORE_BWR.o" "build\CORE_CPP.o" "build\CORE_DE.o" "build\CORE_ECS.o" "build\CORE_FEQ.o" "build\CCMD.o"
	$(FC) -o "CCMD.exe" -static "build\CORE_MLT.o" "build\CORE_PH0.o" "build\CORE_PR.o" "build\CORE_QUI.o" "build\CORE_STN.o" "build\FLASH2.o" "build\FLSH_SUB.o" "build\IDEALGAS.o" "build\MIX_AGA8.o" "build\MIX_HMX.o" "build\PROP_SUB.o" "build\REALGAS.o" "build\SAT_SUB.o" "build\SETUP.o" "build\SETUP2.o" "build\TRNS_ECS.o" "build\TRNS_TCX.o" "build\TRNS_VIS.o" "build\TRNSP.o" "build\UTILITY.o" "build\CORE_ANC.o" "build\CORE_BWR.o" "build\CORE_CPP.o" "build\CORE_DE.o" "build\CORE_ECS.o" "build\CORE_FEQ.o" "build\CCMD.o" $(LDIR) $(PRJ_LFLAGS)

all: "CCMD.exe" .SYMBOLIC

